### ISSUE TITLE
The bookmarklet doesn't work with old.reddit and other subdomains

### ISSUE THREAD

**Issue by 07416** [revddit/revddit#3]
`javascript:window.fetch('https://www.reddit.com/api/me.json').then(response => response.json()).then(response => { let name = response.data.name; if (name) {window.location.href = `http://revddit.com/user/${response.data.name}`} else {window.location.href = 'https://www.reddit.com/login'}})`

**Comment by rhaksw** [comment]
Hi, for old reddit you can change `www.reddit.com` to say `old.reddit.com` and then it will work. I believe this is due to CORS rules.

Another option is to use the [revddit linker](https://github.com/revddit/revddit-linker) extension.
