### ISSUE TITLE
The "message mods" feature is missing "/r/", sends a private message to a Reddit user instead

### ISSUE THREAD

**Issue by 07416** [revddit/revddit#4]
See any user page with deleted content. From Reddit's `https://www.reddit.com/message/compose` page:

>send a private message to (username, or /r/name for that subreddit's moderators)

Revddit doesn't prefix the `to` field with `/r/`, hence the private message is sent to a user instead of the subreddit by default.

For example on /r/firefox/, the PM would be sent to [the user "firefox"](https://www.reddit.com/user/firefox), unless that path is manually added.

**Comment by rhaksw** [comment]
Thanks!
